package com.HundredExample.assignment.runner;

import com.HundredExample.assignment.internal.*;

public class Main {
    public static void main(String[] args) {
        Account account1 = new Account1();
        Account account2 = new Account2();
        Account account3 = new Account3();
        Account account4 = new Account4();
        Account account5 = new Account5();
        Account account6 = new Account6();
        Account account7 = new Account7();
        Account account8 = new Account8();
        Account account9 = new Account9();
        Account account10 = new Account10();
        Account account11 = new Account11();
        Account account12 = new Account12();
        Account account13 = new Account13();
        Account account14 = new Account14();
        Account account15 = new Account15();
        Account account16 = new Account16();
        Account account17 = new Account17();
        Account account18 = new Account18();
        Account account19 = new Account19();
        Account account20 = new Account20();
        Account account21 = new Account21();
        Account account22 = new Account22();
        Account account23 = new Account23();
        Account account24 = new Account24();
        Account account25 = new Account25();
        Account account26 = new Account26();
        Account account27 = new Account27();
        Account account28 = new Account28();
        Account account29 = new Account29();
        Account account30 = new Account30();
        Account account31 = new Account31();
        Account account32 = new Account32();
        Account account33 = new Account33();
        Account account34 = new Account34();
        Account account35 = new Account35();
        Account account36 = new Account36();
        Account account37 = new Account37();
        Account account38 = new Account38();
        Account account39 = new Account39();
        Account account40 = new Account40();
        Account account41 = new Account41();
        Account account42 = new Account42();
        Account account43 = new Account43();
        Account account44 = new Account44();
        Account account45 = new Account45();
        Account account46 = new Account46();
        Account account47 = new Account47();
        Account account48 = new Account48();
        Account account49 = new Account49();
        Account account50 = new Account50();

        Account account51 = new Account51();
        Account account52 = new Account52();
        Account account53 = new Account53();
        Account account54 = new Account54();
        Account account55 = new Account55();
        Account account56 = new Account56();
        Account account57 = new Account57();
        Account account58 = new Account58();
        Account account59 = new Account59();
        Account account60 = new Account60();
        Account account61 = new Account61();
        Account account62 = new Account62();
        Account account63 = new Account63();
        Account account64 = new Account64();
        Account account65 = new Account65();
        Account account66 = new Account66();
        Account account67 = new Account67();
        Account account68 = new Account68();
        Account account69 = new Account69();
        Account account70 = new Account70();
        Account account71 = new Account71();
        Account account72 = new Account72();
        Account account73 = new Account73();
        Account account74 = new Account74();
        Account account75 = new Account75();
        Account account76 = new Account76();
        Account account77 = new Account77();
        Account account78 = new Account78();
        Account account79 = new Account79();
        Account account80 = new Account80();
        Account account81 = new Account81();
        Account account82 = new Account82();
        Account account83 = new Account83();
        Account account84 = new Account84();
        Account account85 = new Account85();
        Account account86 = new Account86();
        Account account87 = new Account87();
        Account account88 = new Account88();
        Account account89 = new Account89();
        Account account90 = new Account90();
        Account account91 = new Account91();
        Account account92 = new Account92();
        Account account93 = new Account93();
        Account account94 = new Account94();
        Account account95 = new Account95();
        Account account96 = new Account96();
        Account account97 = new Account97();
        Account account98 = new Account98();
        Account account99 = new Account99();
        Account account100 = new Account100();

        System.out.println(account1);
        System.out.println(account2);
        System.out.println(account3);
        System.out.println(account4);
        System.out.println(account5);
        System.out.println(account6);
        System.out.println(account7);
        System.out.println(account8);
        System.out.println(account9);
        System.out.println(account10);
        System.out.println(account11);
        System.out.println(account12);
        System.out.println(account13);
        System.out.println(account14);
        System.out.println(account15);
        System.out.println(account16);
        System.out.println(account17);
        System.out.println(account18);
        System.out.println(account19);
        System.out.println(account20);
        System.out.println(account21);
        System.out.println(account22);
        System.out.println(account23);
        System.out.println(account24);
        System.out.println(account25);
        System.out.println(account26);
        System.out.println(account27);
        System.out.println(account28);
        System.out.println(account29);
        System.out.println(account30);
        System.out.println(account31);
        System.out.println(account32);
        System.out.println(account33);
        System.out.println(account34);
        System.out.println(account35);
        System.out.println(account36);
        System.out.println(account37);
        System.out.println(account38);
        System.out.println(account39);
        System.out.println(account40);
        System.out.println(account41);
        System.out.println(account42);
        System.out.println(account43);
        System.out.println(account44);
        System.out.println(account45);
        System.out.println(account46);
        System.out.println(account47);
        System.out.println(account48);
        System.out.println(account49);
        System.out.println(account50);
        System.out.println(account51);
        System.out.println(account52);
        System.out.println(account53);
        System.out.println(account54);
        System.out.println(account55);
        System.out.println(account56);
        System.out.println(account57);
        System.out.println(account58);
        System.out.println(account59);
        System.out.println(account60);
        System.out.println(account61);
        System.out.println(account62);
        System.out.println(account63);
        System.out.println(account64);
        System.out.println(account65);
        System.out.println(account66);
        System.out.println(account67);
        System.out.println(account68);
        System.out.println(account69);
        System.out.println(account70);
        System.out.println(account71);
        System.out.println(account72);
        System.out.println(account73);
        System.out.println(account74);
        System.out.println(account75);
        System.out.println(account76);
        System.out.println(account77);
        System.out.println(account78);
        System.out.println(account79);
        System.out.println(account80);
        System.out.println(account81);
        System.out.println(account82);
        System.out.println(account83);
        System.out.println(account84);
        System.out.println(account85);
        System.out.println(account86);
        System.out.println(account87);
        System.out.println(account88);
        System.out.println(account89);
        System.out.println(account90);
        System.out.println(account91);
        System.out.println(account92);
        System.out.println(account93);
        System.out.println(account94);
        System.out.println(account95);
        System.out.println(account96);
        System.out.println(account97);
        System.out.println(account98);
        System.out.println(account99);
        System.out.println(account100);
    }
}
