package assignment;

public class Main {
    public static void main(String[] args) {
        TeaShop teaShop = new TeaShop();

        // Creating 100 different Account types (Account1 to Account100)
        Account account1 = new Account1();
        Account account2 = new Account2();
        Account account3 = new Account3();
        Account account4 = new Account4();
        Account account5 = new Account5();
        Account account6 = new Account6();
        Account account7 = new Account7();
        Account account8 = new Account8();
        Account account9 = new Account9();
        Account account10 = new Account10();
        Account account11 = new Account11();
        Account account12 = new Account12();
        Account account13 = new Account13();
        Account account14 = new Account14();
        Account account15 = new Account15();
        Account account16 = new Account16();
        Account account17 = new Account17();
        Account account18 = new Account18();
        Account account19 = new Account19();
        Account account20 = new Account20();
        Account account21 = new Account21();
        Account account22 = new Account22();
        Account account23 = new Account23();
        Account account24 = new Account24();
        Account account25 = new Account25();
        Account account26 = new Account26();
        Account account27 = new Account27();
        Account account28 = new Account28();
        Account account29 = new Account29();
        Account account30 = new Account30();
        Account account31 = new Account31();
        Account account32 = new Account32();
        Account account33 = new Account33();
        Account account34 = new Account34();
        Account account35 = new Account35();
        Account account36 = new Account36();
        Account account37 = new Account37();
        Account account38 = new Account38();
        Account account39 = new Account39();
        Account account40 = new Account40();
        Account account41 = new Account41();
        Account account42 = new Account42();
        Account account43 = new Account43();
        Account account44 = new Account44();
        Account account45 = new Account45();
        Account account46 = new Account46();
        Account account47 = new Account47();
        Account account48 = new Account48();
        Account account49 = new Account49();
        Account account50 = new Account50();
        Account account51 = new Account51();
        Account account52 = new Account52();
        Account account53 = new Account53();
        Account account54 = new Account54();
        Account account55 = new Account55();
        Account account56 = new Account56();
        Account account57 = new Account57();
        Account account58 = new Account58();
        Account account59 = new Account59();
        Account account60 = new Account60();
        Account account61 = new Account61();
        Account account62 = new Account62();
        Account account63 = new Account63();
        Account account64 = new Account64();
        Account account65 = new Account65();
        Account account66 = new Account66();
        Account account67 = new Account67();
        Account account68 = new Account68();
        Account account69 = new Account69();
        Account account70 = new Account70();
        Account account71 = new Account71();
        Account account72 = new Account72();
        Account account73 = new Account73();
        Account account74 = new Account74();
        Account account75 = new Account75();
        Account account76 = new Account76();
        Account account77 = new Account77();
        Account account78 = new Account78();
        Account account79 = new Account79();
        Account account80 = new Account80();
        Account account81 = new Account81();
        Account account82 = new Account82();
        Account account83 = new Account83();
        Account account84 = new Account84();
        Account account85 = new Account85();
        Account account86 = new Account86();
        Account account87 = new Account87();
        Account account88 = new Account88();
        Account account89 = new Account89();
        Account account90 = new Account90();
        Account account91 = new Account91();
        Account account92 = new Account92();
        Account account93 = new Account93();
        Account account94 = new Account94();
        Account account95 = new Account95();
        Account account96 = new Account96();
        Account account97 = new Account97();
        Account account98 = new Account98();
        Account account99 = new Account99();
        Account account100 = new Account100();

        // Calling debit for all accounts
        teaShop.debit(account1);
        teaShop.debit(account2);
        teaShop.debit(account3);
        teaShop.debit(account4);
        teaShop.debit(account5);
        teaShop.debit(account6);
        teaShop.debit(account7);
        teaShop.debit(account8);
        teaShop.debit(account9);
        teaShop.debit(account10);
        teaShop.debit(account11);
        teaShop.debit(account12);
        teaShop.debit(account13);
        teaShop.debit(account14);
        teaShop.debit(account15);
        teaShop.debit(account16);
        teaShop.debit(account17);
        teaShop.debit(account18);
        teaShop.debit(account19);
        teaShop.debit(account20);
        teaShop.debit(account21);
        teaShop.debit(account22);
        teaShop.debit(account23);
        teaShop.debit(account24);
        teaShop.debit(account25);
        teaShop.debit(account26);
        teaShop.debit(account27);
        teaShop.debit(account28);
        teaShop.debit(account29);
        teaShop.debit(account30);
        teaShop.debit(account31);
        teaShop.debit(account32);
        teaShop.debit(account33);
        teaShop.debit(account34);
        teaShop.debit(account35);
        teaShop.debit(account36);
        teaShop.debit(account37);
        teaShop.debit(account38);
        teaShop.debit(account39);
        teaShop.debit(account40);
        teaShop.debit(account41);
        teaShop.debit(account42);
        teaShop.debit(account43);
        teaShop.debit(account44);
        teaShop.debit(account45);
        teaShop.debit(account46);
        teaShop.debit(account47);
        teaShop.debit(account48);
        teaShop.debit(account49);
        teaShop.debit(account50);
        teaShop.debit(account51);
        teaShop.debit(account52);
        teaShop.debit(account53);
        teaShop.debit(account54);
        teaShop.debit(account55);
        teaShop.debit(account56);
        teaShop.debit(account57);
        teaShop.debit(account58);
        teaShop.debit(account59);
        teaShop.debit(account60);
        teaShop.debit(account61);
        teaShop.debit(account62);
        teaShop.debit(account63);
        teaShop.debit(account64);
        teaShop.debit(account65);
        teaShop.debit(account66);
        teaShop.debit(account67);
        teaShop.debit(account68);
        teaShop.debit(account69);
        teaShop.debit(account70);
        teaShop.debit(account71);
        teaShop.debit(account72);
        teaShop.debit(account73);
        teaShop.debit(account74);
        teaShop.debit(account75);
        teaShop.debit(account76);
        teaShop.debit(account77);
        teaShop.debit(account78);
        teaShop.debit(account79);
        teaShop.debit(account80);
        teaShop.debit(account81);
        teaShop.debit(account82);
        teaShop.debit(account83);
        teaShop.debit(account84);
        teaShop.debit(account85);
        teaShop.debit(account86);
        teaShop.debit(account87);
        teaShop.debit(account88);
        teaShop.debit(account89);
        teaShop.debit(account90);
        teaShop.debit(account91);
        teaShop.debit(account92);
        teaShop.debit(account93);
        teaShop.debit(account94);
        teaShop.debit(account95);
        teaShop.debit(account96);
        teaShop.debit(account97);
        teaShop.debit(account98);
        teaShop.debit(account99);
        teaShop.debit(account100);
    }
}
